.travis.yml
=> Fix the branches.only setting

controller/helper.php, controller/taskscontroller.php
Based on the pull request #159 by @PVince81 I fixed an issue which I described on his pull request.
The reponses of the requests
```
http://localhost:8080/index.php/apps/tasks/tasks/init/all
http://localhost:8080/index.php/apps/tasks/tasks/add
```
were empty because the Sabre\VObject creates recursions in vtodos in form of parent and child relations.
=> Fixing the update for Sabre 2.1

appinfo/update.php, controller/helper.php, controller/searchcontroller.php, controller/taskscontroller.php, css/style.css, css/style.less
- get rid of OC_VObject
- adapt date handling
- replace setString/getAsString usages
This is needed for the app to work with (core/master) and the upcoming 8.1 which contains the Sabre upgrade to 2.1.
Note: the app still doesn't work and I don't know, needs more debugging
=> Update for Sabre 2.1

css/style.css, css/style.less, js/app/app.coffee, js/app/controllers/appcontroller.coffee, js/app/controllers/listcontroller.coffee, js/app/directives/autofocusoninsert.coffee, js/public/app.js, templates/main.php
I readded the missing renaming functionality for lists.
In my opinion the only remaining problem is, that switching from renaming to adding a list doesn't close the previous input. This has something to do with `handler` and `close-all`.
@raimund-schluessler Maybe you can give me a hint on how to solve this.
=> Fix list editing

css/vendor/bootstrap/bootstrap.css
removed bracket from bootstrap.css
=> removed bracket

controller/helper.php
=> Fixed new tasks being starred by default

.travis.yml, appinfo/application.php, controller/taskscontroller.php, service/tasksservice.php
I proposed similar changes before the sabre/vobject changes #158.
This moves most of the functionality out of taskscontroller.php into tasksservice.php.
=> move functionality from taskscontroller to service

controller/helper.php, controller/searchcontroller.php, service/tasksservice.php
Clean version of the messed up #198
=> check privacy for shared tasks (second try)

appinfo/routes.php, controller/helper.php, controller/taskscontroller.php, css/style.css, css/style.less, img/sprites.svg, js/app/controllers/detailscontroller.coffee, js/app/filters/priorityDetails.coffee, js/app/services/businesslayer/tasksbusinesslayer.coffee, js/app/services/models/tasksmodel.coffee, js/app/services/persistence.coffee, js/public/app.js, service/tasksservice.php, templates/part.collectionall.php, templates/part.collectionweek.php, templates/part.details.php, templates/part.tasklist.php
=> Implement priority support

appinfo/application.php, controller/collectionscontroller.php, controller/listscontroller.php, controller/settingscontroller.php, controller/taskscontroller.php, service/collectionsservice.php, service/listsservice.php, service/settingsservice.php, service/tasksservice.php
This pull request cleans up the tasks service implementation and adds services for lists, collections and settings.
=> Further work on the services

controller/helper.php, controller/searchcontroller.php, service/tasksservice.php
I removed all usages of magic methods (functions with a double underscore).
This doesn't change any functionality. It's just best practice to not use them.
=> Remove magic methods

controller/helper.php, controller/response.php, controller/taskscontroller.php, js/app/controllers/detailscontroller.coffee, js/app/controllers/taskscontroller.coffee, js/public/app.js, service/tasksservice.php
This pull request adds a response trait as discussed in #205.
These changes unify the requests/responses as described in #196.
=> Response Trait

appinfo/app.php, appinfo/application.php, controller/helper.php, controller/searchcontroller.php, service/tasksservice.php
This removes some deprecated functions and constants.
I didn't touch the update.php as I have no idea what to do over there.
=> Replaced deprecated functions

css/style.css, css/style.less
fixes #188
@jancborchardt please have a look at this.
=> Shortened animations

js/app/app.coffee, js/app/filters/dateDetails.coffee, js/app/filters/dateDetailsShort.coffee, js/app/filters/dateTaskList.coffee, js/app/filters/day.coffee, js/app/filters/dayTaskList.coffee, js/app/filters/reminderDetails.coffee, js/app/filters/startDetails.coffee, js/app/services/businesslayer/tasksbusinesslayer.coffee, js/public/app.js
Replaced all occurrences of lang() with locale().
=> Replaced deprecated moment.js functions

appinfo/application.php
Fixing the problem that forwarding to login page failed while not logged in.
=> Fix forwarding error while not logged in

css/style.css
As discussed @raimund-schluessler @Henni
Before:
After:
=> correctly intend input content to match with other text, and unbold it

appinfo/app.php, js/calendar-missing.js
Fix #249 
@Henni @raimund-schluessler for now this is okay, but ideal world you'd not have to have a calendar, if possible ;)
=> Add visual feedback about missing dependency

appinfo/app.php, appinfo/application.php
=> Fix registering the search provider

js/app/controllers/taskscontroller.coffee, js/public/app.js, service/taskparser.php
Should fix the sort order of tasks, closes #233.
=> Fix taskorder

css/style.css
Closes #237 
@Henni Please have a look.
=> Fix priority and completed input on chrome

appinfo/info.xml
=> Upgrade max-version to 9.0 in appinfo

js/app/controllers/taskscontroller.coffee, js/app/services/models/tasksmodel.coffee, js/public/app.js, templates/part.taskbody.php
=> Temporally show subtasks when task open

css/style.css, js/app/controllers/listcontroller.js, js/app/services/models/calendar.js, js/public/app.js, templates/main.php
Add possibility to export a calendar and to show the CalDAV Url
=> Add CalDAV-Link and export function

css/style.css, img/source/alphabetically.svg, img/source/manual.svg, img/sprites.svg, js/app/controllers/taskscontroller.js, js/app/services/persistence.js, js/public/app.js, service/settingsservice.php, templates/main.php, templates/part.collectionall.php, templates/part.collectionweek.php, templates/part.taskbody.php, templates/part.tasklist.php
This PR enables the custom sorting of the task list. It will be possible to sort the task list by:
- the default sorting order
- by due date
- by start date
- by priority
- alphabetically by task name
- manually by drag and drop
The last option will be implemented in a following PR and will be hidden until then.
Solves https://github.com/owncloud/tasks/issues/294 and https://github.com/owncloud/tasks/issues/86 partially.
TODO:
=> Allow different sort criteria

js/app/controllers/taskscontroller.js, js/app/services/models/vtodo.js, js/public/app.js
This tasks fixes the direct creation of important, current and due tasks, closes #359.
=> Fix creating important, current and due tasks, closes #359

README.md
Inform the people that this old repository has been moved to Nextcloud.
@raimund-schluessler Please review/merge.
=> We have moved to Nextcloud

appinfo/info.xml
in refrence to issue  #382 
modified info.xml
=> added support for v10.0 

.travis.yml
=> Add php 7.2, 7.1 and 7.0
